# Generated by Django 5.0.4 on 2024-08-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
