# Generated by Django 5.0.4 on 2024-08-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_friend_friendrequest_post_like_comment_delete_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
