# Generated by Django 5.0.4 on 2024-08-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uid',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='posts'),
        ),
    ]
