# Generated by Django 5.0.4 on 2024-08-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_comments_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='uid',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
