# Generated by Django 5.0.4 on 2024-08-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_otp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='connection_uid',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
